version: "3.9"
services:
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  web:
    image: "leondesilva/product-service:v2"
    ports:
      - "9000:9000"